FROM arm32v7/debian:buster-slim

RUN apt-get -y update && apt-get -y install rtorrent && \
    mkdir -p /rtorrent/config.d && \
    mkdir /rtorrent/.session && \
    mkdir /rtorrent/temp && \
    mkdir /rtorrent/download && \
    mkdir /rtorrent/watch

COPY config.d/ /rtorrent/config.d/
COPY .rtorrent.rc /root/

# This volume make it easier to delete rtorrent lock files after a bad shutdown.
VOLUME /rtorrent/.session

EXPOSE 16891
EXPOSE 6881
EXPOSE 50000

CMD ["rtorrent"]
